version: '3.8'
volumes:
  data:


services: 
  landpage:
    build:
      dockerfile: ./Dockerfile
    container_name: landpage
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./src:/usr/src/app/src
    